### ISSUE TITLE
TEST-PARSING-GOOD-TEST-FILES fails in SBCL: The value #.CL-QUIL:QUIL-REAL is not of type LIST

### ISSUE THREAD

**Issue by mhdavid-hrl** [quil-lang/quilc#770]
In SBCL (or probably any non-Allegro Lisp) tests for cl-quil fail in test `TEST-PARSING-GOOD-TEST-FILES`, subpart "Testing good file good-classical-arithmetic".
The error message is:
```
The value #.CL-QUIL:QUIL-REAL is not of type LIST when binding LIST
```

To recreate, run the cl-quil tests, e.g., in Lisp
```
(ql:quickload :cl-quil-tests)
(asdf:test-system :cl-quil)
```
or in repo at top level:
```
make test-cl-quil
```

**Comment by mhdavid-hrl** [comment]
I isolated this down to commit 07208da `support AllegroCL 10.1 (Part I)`, which is at this time the most recent commit on `master` (main branch).
This commit was the one commit of PR `support AllegroCL 10.1 (Part I)` #767.
That PR did not pass CI checks, but the failure was due to the version issue with magicl, not this error. The version issue with magicl is that it says
```
Component #:MAGICL/CORE does not match version 0.10.0, required by #<SYSTEM "cl-quil">
```
but we know this is just a limitation of our CI and the fact that it gets an old version of magical from Quicklisp. (That's a separate issue.)
In addition, the developer @franzinc stated "All tests passed for both Allegro and SBCL in a 64-bit Linux". Not sure if that was erroneous or perhaps there was some compiler or other environment setting that was used that was more forgiving. At any rate, presumably due to the above reasons, the CI checks requirement was waived (by @stylewarning).

**Comment by mhdavid-hrl** [comment]
The bug seems to be caused by code changes explained by @macdavid313 in this PR files comment: https://github.com/quil-lang/quilc/pull/767/files#r745348410
The code was changed to use APPLY, but there's no list of args in the non-allegro case, which leads to the bug.

**Comment by macdavid313** [comment]
Apologies. It is a bug indeed.

**Comment by macdavid313** [comment]
@mhdavid-hrl Are you available to create a quick fix from your side? As long as `:test 'euqalp` is specified in the case of Allegro, it'd be OK.

**Comment by macdavid313** [comment]
[PR](https://github.com/quil-lang/quilc/pull/771) created.

**Comment by mhdavid-hrl** [comment]
PR #771 resolved this issue, so closing this now.
