### ISSUE TITLE
Expose basic Quilc functionality via a C API

### ISSUE THREAD

**Issue by kartik-s** [quil-lang/quilc#788]
# Problem
I want to be able to use Quilc as a shared library, e.g. `libquilc.[so|dll|dylib]`. This would serve as lighter alternative to the existing RPC server mode for users who want to use Quilc from other langauges like C or Python, especially when working on a single local machine.

# Scope
As a first pass, I am proposing that this shared library should expose Quilc functionality for:
- parsing and printing Quil programs
- creating basic chip specifications
- compiling Quil/ProtoQuil programs

This is a small but useful set of functionality to begin working off of.

# Solution
We can use [sbcl-librarian](https://github.com/quil-lang/sbcl-librarian) to expose Quilc functionality as a shared library.

**Comment by stylewarning** [comment]
This sounds like a good blueprint for starting a C API effort with quilc. Exciting!

**Comment by karlosz** [comment]
We'll probably want a higher level Python API to wrap this functionality as well.
