### ISSUE TITLE
remove randomization in `find-diagonalizer-in-e-basis`

### ISSUE THREAD

**Issue by stylewarning** [quil-lang/quilc#847]
I don't think the `F-D-I-E-B` is a "probabilistic algorithm" in the traditional sense (i.e., we don't need randomness to asymptotically converge to something), we just need numbers that break possible degenerate relationships between the Re and Im part. I propose we replace the RNG with something aperiodic but deterministic sequence like $r_k = \vert\sin \frac{k}{10}\vert$ for $k=1,2,\ldots$. This sequence will get arbitrarily close to every value in $[0,1]$, but that probably matters only to the theoretician.

**Comment by ecpeterson** [comment]
👍
