### ISSUE TITLE
New release required for Quicklisp

### ISSUE THREAD

**Issue by quicklisp** [quil-lang/quilc#892]
Building with SBCL 2.3.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 1309e19ae3c3b6fc0d8eaa9514f45b0695d0c2b9

*boondoggle-tests* fails to build because of a failure in  _cl-quil_.

*boondoggle* fails to build because of a failure in  _cl-quil_.

*cl-quil-benchmarking* fails to build because of a failure in  _cl-quil_.

*cl-quil-tests* fails to build because of a failure in  _cl-quil_.

*cl-quil* fails to build with the following error:

```
; caught WARNING:
;   The function CL-PERMUTATION::%MAKE-PERM is called with two arguments, but wants exactly one.
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=1042807 "main thread" RUNNING {1001770003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-quil" "clifford" "perm">

```

*cl-quil/quilec-tests* fails to build because of a failure in  _cl-quil_.

*cl-quil/quilec* fails to build because of a failure in  _cl-quil_.

*cl-quil/quilt-tests* fails to build because of a failure in  _cl-quil_.

*cl-quil/quilt* fails to build because of a failure in  _cl-quil_.

*cl-quil/tools-tests* fails to build because of a failure in  _cl-quil_.

*cl-quil/tools* fails to build because of a failure in  _cl-quil_.

*quilc-tests* fails to build because of a failure in  _cl-quil_.

*quilc* fails to build because of a failure in  _cl-quil_.

[Full log here](http://report.quicklisp.org/2023-07-22/failure-report/quilc.html)

**Comment by stylewarning** [comment]
Thanks, will get these fixed.

**Comment by stylewarning** [comment]
Fixed in 1937530. Let me know if there are other issues.

**Comment by quicklisp** [comment]
I won't be able to compile the fix without a new release.

**Comment by stylewarning** [comment]
done

**Comment by quicklisp** [comment]
You made a new tag but not a new release.

**Comment by quicklisp** [comment]
Same problem with magicl also.
